# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\"\x13\n\x03Tag\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xda\x01\n\x05\x45vent\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12\x1d\n\x06status\x18\x05 \x01(\x0e\x32\r.Event.Status\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\x12\x12\n\x04tags\x18\x08 \x03(\x0b\x32\x04.Tag\"2\n\x06Status\x12\x0c\n\x08\x43\x61nceled\x10\x00\x12\x0b\n\x07Pending\x10\x01\x12\r\n\tConfirmed\x10\x02\"#\n\tEventList\x12\x16\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x06.Eventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TAG']._serialized_start=16
  _globals['_TAG']._serialized_end=35
  _globals['_EVENT']._serialized_start=38
  _globals['_EVENT']._serialized_end=256
  _globals['_EVENT_STATUS']._serialized_start=206
  _globals['_EVENT_STATUS']._serialized_end=256
  _globals['_EVENTLIST']._serialized_start=258
  _globals['_EVENTLIST']._serialized_end=293
# @@protoc_insertion_point(module_scope)
